# Generated by Django 5.2.4 on 2025-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
